// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFBAXAEUXHfhvm4x3rp7sUSinNUE7U84',
    appId: '1:662503190424:android:5f283dc532dd01474745ed',
    messagingSenderId: '662503190424',
    projectId: 'notification-demo-bb78f',
    storageBucket: 'notification-demo-bb78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Jh5EcLDto4krRGN_BR4j8bwaCEVJJ10',
    appId: '1:662503190424:ios:38444fcf9b523f694745ed',
    messagingSenderId: '662503190424',
    projectId: 'notification-demo-bb78f',
    storageBucket: 'notification-demo-bb78f.appspot.com',
    iosClientId: '662503190424-pijvvplq05muejknel9ml8bjgbvdfm92.apps.googleusercontent.com',
    iosBundleId: 'com.evidentbd.notification',
  );
}
